version: "3.9"

services:
  db:
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/dued
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/dued
    networks:
      - skynet

  odoo:
    image: ${ODOO_IMAGE}
    platform: linux/amd64
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports: ["8090:8069"]
    depends_on:
      - db
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
      - ./etc/odoo.conf:/etc/odoo/odoo.conf
    networks:
      - skynet

  # nginx:
  #   image: ${NGINX_IMAGE}
  #   depends_on:
  #     - odoo
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - nginx-logs:/var/log/nginx
  #     - ./nginx-conf:/etc/nginx/conf.d:ro
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #     - /etc/ssl/certs:/etc/ssl/certs:ro

volumes:
  odoo-db-data:
  odoo-web-data:
  nginx-logs:

networks:
  skynet:
